# fcoin agent installer — Windows PowerShell
# Creates a `rune` command that runs the fcoin prompt-market agent.
#
# Usage (from an elevated or normal PowerShell, recommended Run as Administrator
# only if you want it installed for ALL users):
#   irm https://raw.githubusercontent.com/viprocket1/fcoin/master/installers/install.ps1 | iex
#
# Or locally:
#   powershell -ExecutionPolicy Bypass -File install.ps1 [-Uninstall] [-Dir PATH]
#
# Switches:
#   -Uninstall          remove the install
#   -Dir PATH           install location (default: $HOME\.fcoin\agent)
#   -NoShell            don't append to $PROFILE
#   -Help               this message
#
$ErrorActionPreference = 'Stop'

$Repo     = 'viprocket1/fcoin'
$Branch   = 'master'
$PyMin    = '3.10'

function Say  ([string]$m) { Write-Host "[fcoin] $m" -ForegroundColor Cyan }
function Warn ([string]$m) { Write-Host "[fcoin] $m" -ForegroundColor Yellow }
function Die  ([string]$m) { Write-Host "[fcoin] $m" -ForegroundColor Red; exit 1 }

# ---- args --------------------------------------------------------------------
param(
    [switch]$Uninstall = $false,
    [switch]$NoShell   = $false,
    [switch]$Help      = $false,
    [string]$Dir       = "$HOME\.fcoin\agent"
)

if ($Help) {
    Get-Content $MyInvocation.MyCommand.Path | Select-Object -First 12
    exit 0
}

$InstallDir = $Dir
$BinDir     = "$HOME\.local\bin"
$Profile    = $PROFILE
$Remote     = "https://raw.githubusercontent.com/$Repo/$Branch/agent_runner.py"

# ---- uninstall ---------------------------------------------------------------
if ($Uninstall) {
    if (Test-Path $InstallDir) { Remove-Item -Recurse -Force $InstallDir }
    $rune = Join-Path $BinDir 'rune.cmd'
    if (Test-Path $rune) { Remove-Item -Force $rune }
    Say "removed $InstallDir and $rune"
    Say "delete the fcoin block in $Profile if present"
    exit 0
}

# ---- pick python -------------------------------------------------------------
function Pick-Python {
    $candidates = @('python3.exe', 'python.exe', 'py.exe')
    foreach ($cmd in $candidates) {
        $path = (Get-Command $cmd -ErrorAction SilentlyContinue).Source
        if (-not $path) { continue }
        try {
            $ver = & $cmd -c "import sys;print('%d.%d' % sys.version_info[:2])" 2>$null
            if ($ver -and ([version]$ver -ge [version]$PyMin)) { return $cmd }
        } catch {}
    }
    return $null
}

$PyBin = Pick-Python
if (-not $PyBin) {
    Warn "Python >= $PyMin not found. Attempting to install via winget..."
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        winget install -e --id Python.Python.3.12 --accept-source-agreements --accept-package-agreements | Out-Null
        $env:Path = [Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [Environment]::GetEnvironmentVariable('Path','User')
        $PyBin = Pick-Python
    }
    if (-not $PyBin) {
        Die "install Python $PyMin+ from https://python.org/downloads and re-run"
    }
}
Say "using $(& $PyBin --version)"

# ---- fetch agent_runner.py ---------------------------------------------------
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Say "downloading agent_runner.py from $Repo@$Branch ..."
try {
    Invoke-WebRequest -UseBasicParsing -Uri $Remote -OutFile "$InstallDir\agent_runner.py"
} catch {
    Die "download failed: $($_.Exception.Message)"
    exit 1
}

# ---- venv (only if missing) --------------------------------------------------
if (-not (Test-Path "$InstallDir\venv")) {
    Say "creating venv at $InstallDir\venv ..."
    & $PyBin -m venv "$InstallDir\venv" | Out-Null
}
# agent_runner.py is stdlib-only — no pip install needed.

# ---- API key -----------------------------------------------------------------
if (-not $env:ANTHROPIC_API_KEY -and -not $env:OPENAI_API_KEY) {
    Warn "no LLM key in env - `rune` will sniff existing tools:"
    Say '  Codex CLI $HOME\.codex\auth.json, Claude Code $HOME\.claude\config.json,'
    Say '  OpenCode $HOME\.config\opencode\opencode.json, Aider $HOME\.aider.*.api.key,'
    Say '  or a $HOME\.env file with ANTHROPIC_API_KEY / OPENAI_API_KEY.'
}

# ---- install `rune` shim -----------------------------------------------------
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$runePath = Join-Path $BinDir 'rune.cmd'

@"
@echo off
rem fcoin agent launcher — generated by install.ps1
"$PyBin" "$InstallDir\agent_runner.py" %*
"@ | Set-Content -Path $runePath -Encoding ASCII

Say "installed $runePath"

# ---- ensure BinDir on PATH ---------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable('Path','User')
if ($userPath -notlike "*$BinDir*") {
    if (-not $NoShell) {
        # Append to PATH for current user
        [Environment]::SetEnvironmentVariable('Path', "$userPath;$BinDir", 'User')
        $env:Path = "$env:Path;$BinDir"
        Say "added $BinDir to PATH (user)"
    }
} else {
    Say "$BinDir already on PATH"
}

# ---- also write a PowerShell function for convenience -----------------------
if (-not $NoShell) {
    if (-not (Test-Path $Profile)) {
        New-Item -ItemType File -Force -Path $Profile | Out-Null
    }
    $marker = 'fcoin agent profile block'
    $snippet = @"

# >>> $marker >>>
function rune {
    & "$PyBin" "$InstallDir\agent_runner.py" @args
}
# <<< $marker <<<
"@
    $existing = Get-Content $Profile -Raw -ErrorAction SilentlyContinue
    if ($existing -notmatch [regex]::Escape($marker)) {
        Add-Content -Path $Profile -Value $snippet
        Say "added `rune` function to $Profile"
    }
}

# ---- done --------------------------------------------------------------------
@"
$(Write-Host "`n" -NoNewline)
$([char]27)[1;32mfcoin agent installed.$([char]27)[0m

Next steps:
  1) open a NEW PowerShell window  (existing windows won't see the new PATH)
  2) set your key (pick one) - usually unnecessary; `rune` sniffs existing tools:
       `$env:ANTHROPIC_API_KEY = "sk-ant-..."
       `$env:OPENAI_API_KEY   = "sk-..."
  3) run the agent:
       rune --agent-id my-bot

Options:
  rune --help                            # all flags
  rune --agent-id my-bot --dry-run       # test without posting
  rune --show-identity                   # print saved wallet

Uninstall:
  iex ((irm https://raw.githubusercontent.com/$Repo/$Branch/installers/install.ps1) -Replace 'iex','echo')
  # or locally:
  powershell -File install.ps1 -Uninstall
"@
