#!/usr/bin/env bash
# fcoin agent installer — Linux / macOS / Termux (bash)
# Creates a `rune` command that runs the fcoin prompt-market agent.
#
# Usage:   curl -fsSL https://raw.githubusercontent.com/viprocket1/fcoin/master/installers/install.sh | bash
# Or:      bash install.sh [--uninstall] [--dir DIR] [--no-shell]
#
set -euo pipefail

REPO="viprocket1/fcoin"
BRANCH="master"
INSTALL_DIR="${HOME}/.fcoin/agent"
BIN_DIR="${HOME}/.local/bin"
SHELL_RC="${HOME}/.bashrc"
PY_MIN="3.10"

say()  { printf '\033[1;36m[fcoin]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[fcoin]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[fcoin]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- arg parsing -------------------------------------------------------------
UNINSTALL=0
EDIT_SHELL=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)  UNINSTALL=1; shift ;;
    --dir)        INSTALL_DIR="$2"; shift 2 ;;
    --no-shell)   EDIT_SHELL=0; shift ;;
    -h|--help)
      sed -n '2,8p' "$0"; exit 0 ;;
    *) die "unknown flag: $1" ;;
  esac
done

# ---- uninstall ---------------------------------------------------------------
if [[ "$UNINSTALL" == "1" ]]; then
  rm -rf "$INSTALL_DIR"
  rm -f  "$BIN_DIR/rune"
  say "removed $INSTALL_DIR and $BIN_DIR/rune"
  say "delete the fcoin block in $SHELL_RC if present"
  exit 0
fi

# ---- pick python -------------------------------------------------------------
pick_python() {
  for cmd in python3 python; do
    if command -v "$cmd" >/dev/null 2>&1; then
      local ver
      ver="$("$cmd" -c 'import sys;print("%d.%d"%sys.version_info[:2])' 2>/dev/null || echo 0)"
      if [[ "$(echo "$ver >= $PY_MIN" | bc -l 2>/dev/null || echo 0)" == "1" ]]; then
        echo "$cmd"; return 0
      fi
    fi
  done
  return 1
}

if ! PY_BIN="$(pick_python)"; then
  warn "Python >= $PY_MIN not found. Attempting to install..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y && sudo apt-get install -y python3 python3-venv
  elif command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y python3 python3-virtualenv
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y python3 python3-virtualenv
  elif command -v brew >/dev/null 2>&1; then
    brew install python@3.12
  elif command -v pkg >/dev/null 2>&1; then
    pkg update -y && pkg install -y python
  else
    die "no supported package manager — install Python $PY_MIN+ manually"
  fi
  PY_BIN="$(pick_python)" || die "Python still not available after install"
fi
say "using $($PY_BIN --version) at $(command -v $PY_BIN)"

# ---- fetch agent_runner.py ---------------------------------------------------
RAW_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}/agent_runner.py"
mkdir -p "$INSTALL_DIR"
say "downloading agent_runner.py from $REPO@$BRANCH ..."
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$RAW_URL" -o "$INSTALL_DIR/agent_runner.py" \
    || die "download failed — check network or repo access"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$INSTALL_DIR/agent_runner.py" "$RAW_URL" \
    || die "download failed — check network or repo access"
else
  die "need curl or wget to fetch agent_runner.py"
fi
chmod +x "$INSTALL_DIR/agent_runner.py"

# ---- venv (only if missing) --------------------------------------------------
if [[ ! -d "$INSTALL_DIR/venv" ]]; then
  say "creating venv at $INSTALL_DIR/venv ..."
  "$PY_BIN" -m venv "$INSTALL_DIR/venv"
fi
# agent_runner.py uses stdlib only; no pip install needed.

# ---- API key -----------------------------------------------------------------
if [[ -z "${ANTHROPIC_API_KEY:-}" && -z "${OPENAI_API_KEY:-}" ]]; then
  warn "no LLM key in env — `rune` will sniff existing tools:"
  say "  Codex CLI ~/.codex/auth.json, Claude Code ~/.claude/config.json,"
  say "  OpenCode ~/.config/opencode/opencode.json, Aider ~/.aider.*.api.key,"
  say "  or a ~/.env file with ANTHROPIC_API_KEY=... / OPENAI_API_KEY=..."
fi

# ---- install `rune` shim -----------------------------------------------------
# Routing: any subcommand (`update`, `uninstall`, `version`, `status`) goes
# through the installer itself; everything else is forwarded to agent_runner.py.
RAW_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}/installers/install.sh"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/rune" <<EOF
#!/usr/bin/env bash
# fcoin agent launcher + self-updater — generated by install.sh
set -e
cmd="\${1:-}"
case "\$cmd" in
  update|--update|-u)
    echo "[rune] fetching latest installer from ${REPO}@${BRANCH} ..."
    exec curl -fsSL "${RAW_URL}" | bash -s -- "\${@:2}"
    ;;
  uninstall|--uninstall)
    echo "[rune] re-running installer with --uninstall ..."
    exec curl -fsSL "${RAW_URL}" | bash -s -- --uninstall
    ;;
  version|--version|-V)
    echo "fcoin agent_runner.py at: $INSTALL_DIR/agent_runner.py"
    grep -E 'REPO|BRANCH' "$INSTALL_DIR/agent_runner.py" 2>/dev/null | head -3
    echo "installer URL: ${RAW_URL}"
    ;;
  status|doctor)
    echo "INSTALL_DIR = $INSTALL_DIR"
    echo "AGENT_RUNNER = $PY_BIN $INSTALL_DIR/agent_runner.py"
    "\$0" --show-identity 2>/dev/null || true
    ;;
  --help|-h|"")
    echo "Usage: rune [command] [args]"
    echo ""
    echo "Subcommands:"
    echo "  update       re-run installer to fetch latest agent_runner.py"
    echo "  uninstall    remove the agent + shim"
    echo "  status       show install paths and saved agent identity"
    echo "  version      print install paths + installer URL"
    echo ""
    echo "Default: forwards all remaining args to agent_runner.py:"
    echo "  rune --agent-id my-bot"
    echo "  rune --show-identity"
    echo "  rune --dry-run"
    echo "  rune --reset"
    "\$0" --help
    ;;
  *)
    # Everything else (--agent-id, --show-identity, --dry-run, ...) goes to the agent
    exec "$PY_BIN" "$INSTALL_DIR/agent_runner.py" "\$@"
    ;;
esac
EOF
chmod +x "$BIN_DIR/rune"
say "installed $BIN_DIR/rune"

# Save the install URL alongside for debugging / 'rune update' to consult
mkdir -p "$INSTALL_DIR"
echo "INSTALL_URL=${RAW_URL}" > "$INSTALL_DIR/.rune-update-url"

# ---- ensure BIN_DIR on PATH --------------------------------------------------
if [[ "$EDIT_SHELL" == "1" ]]; then
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;  # already on PATH
    *)
      touch "$SHELL_RC" 2>/dev/null || true
      if ! grep -q 'fcoin agent PATH' "$SHELL_RC" 2>/dev/null; then
        {
          echo ''
          echo '# >>> fcoin agent PATH >>>'
          echo 'export PATH="$HOME/.local/bin:$PATH"'
          echo '# <<< fcoin agent PATH <<<'
        } >> "$SHELL_RC"
        say "added $BIN_DIR to PATH in $SHELL_RC"
      fi
      ;;
  esac
fi

# ---- done --------------------------------------------------------------------
cat <<MSG

$(printf '\033[1;32m')fcoin agent installed.$(printf '\033[0m')

Next steps:
  1) restart your shell (or: source $SHELL_RC)
  2) set your key (pick one) — usually unnecessary, `rune` sniffs existing tools:
       export ANTHROPIC_API_KEY=sk-ant-...
       export OPENAI_API_KEY=sk-...
  3) run the agent:
       rune --agent-id my-bot

Options:
  rune                            # run the agent (auto-displays identity on first launch)
  rune --show-identity             # print saved wallet
  rune update                      # self-update: pulls latest agent_runner.py
  rune status                      # show install paths + saved identity
  rune uninstall                   # remove the agent + shim

Uninstall:
  rune uninstall
  # or
  curl -fsSL .../install.sh | bash -s -- --uninstall
MSG
